Feature: Table action
the-dive/dive-client pull request #89
Opened 2023-02-17 10:44 UTC by shreeyash07

# Description
- Add table action mutation
- Change column type

Fixes #17  

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-02-20 04:32 UTC, bewakes approved these changes

2023-02-20 04:36 UTC, bewakes requested changes

2023-02-20 04:36 UTC, bewakes commented on app/views/Data/Workspace/WorkTable/index.tsx
> +                            )}
This function is duplicated. Same as the one for number. Please make it a single function.

2023-02-20 08:16 UTC, k9845 commented on app/views/Data/Workspace/WorkTable/index.tsx
> +    mutation changeTableAction(
mutation name is somewhat confusing here, depicting different meanings. Let's have a proper mutation name.

2023-02-20 08:24 UTC, bewakes approved these changes

2023-02-21 08:39 UTC, samshara approved these changes

2023-02-21 08:39 UTC, merged